export function generateComponentId(prefix: string = 'comp'): string {
  return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

export type {
  ActionButton,
  AIUIResponse,
  ArtifactCreatedPayload,
  ButtonVariant,
  CardItem,
  ComponentInteractionState,
  EditSuggestionPayload,
  ErrorPayload,
  FormField,
  FormFieldType,
  FormGroup,
  ImageProgressPayload,
  ImageResultItem,
  ImageResultPayload,
  LogPayload,
  MarkdownPayload,
  MetaPayload,
  PointsConsumedPayload,
  ProgressPayload,
  PromptSuggestionPayload,
  SelectionOption,
  Step,
  StepArtifactCreatedPayload,
  StepCompletedPayload,
  StepStatus,
  StreamMessage,
  TableColumn,
  TableRow,
  TableRowAction,
  UIAction,
  UIActionButtons,
  UICard,
  UIConfirmation,
  UIForm,
  UIPayload,
  UIResponse,
  UISelection,
  UISteps,
  UIStage,
  UITable,
  UIText,
} from '@autix/domain/ai-ui';
